theme: jekyll-theme-minimal
title: Shuai Han
email: dalen17 at sjtu dot edu dot cn 
description: <br/> dalen17 at sjtu dot edu dot cn <br/> <br/> Assistant professor @ Shanghai Jiao Tong University. Working on cryptography. 
