theme: jekyll-theme-minimal
title: Shuai Han
description: I am an assistant professor at Shanghai Jiao Tong University. <br/> <br/> Previously, I was a postdoc at Karlsruhe Institute of Technology (Germany), hosted by Dennis Hofheinz. Prior to that, I obtained my PhD from Shanghai Jiao Tong University, supervised by Shengli Liu. 
